/home/yunhui/anaconda2/lib/python2.7/site-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "./train_knowledge.py", line 464, in <module>
    test_loop(novel_loader, base_loader, return_std = False)
  File "./train_knowledge.py", line 59, in test_loop
    for i, (x,_) in enumerate(novel_loader):
  File "/home/yunhui/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/yunhui/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/yunhui/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/ssd/yunhui/few_shot/data/dataset.py", line 53, in __getitem__
    return next(iter(self.sub_dataloader[i]))
  File "/home/yunhui/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/ssd/yunhui/few_shot/data/dataset.py", line 68, in __getitem__
    img = Image.open(image_path).convert('RGB')
  File "/home/yunhui/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: u'/ssd/yunhui/CloserLookFewShot/filelists/emnist/inv_emnist/29/153.png'

